site_name: Sparse Autoencoder
site_description: Sparse Autoencoder for Mechanistic Interpretability
docs_dir: docs/content
site_dir: docs/generated
repo_url: https://github.com/ai-safety-foundation/sparse_autoencoder
repo_name: ai-safety-foundation/sparse_autoencoder
edit_uri: "" # Disabled as we use mkdocstrings which auto-generates some pages
strict: true

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right
  features:
    - content.action.edit

extra_javascript:
  - javascript/custom_formatting.js
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - "css/material_extra.css"
  - "css/custom_formatting.css"

markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs/content
  - admonition # Adds admonition blocks (e.g. warning, note, tip, etc.)
  - toc:
      permalink: "¤" # Adds a clickable permalink to each section heading
      toc_depth: 4

plugins:
  - search
  - autorefs
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
  - mknotebooks
  - mkdocstrings: # https://mkdocstrings.github.io
      handlers:
        python:
          setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
            - import jaxtyping
            - jaxtyping.set_array_name_format("array")
          options:
            docstring_style: google
            line_length: 100
            show_symbol_type_heading: true
            edit_uri: ""
  - htmlproofer:
      raise_error: True
