name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
  # Allow this workflow to be called from other workflows
  workflow_call:
    inputs:
      #  Requires at least one input to be valid, but in practice we don't need any
      dummy:
        type: string
        required: false

jobs:
  checs:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
        allow-prereleases: true
    - name: Install dependencies
      run: poetry install --with dev
    - name: Pyright type check
      run: poetry run pyright
    - name: Ruff lint
      run: poetry run ruff check sparse_autoencoder --output-format=github 
    - name: Ruff format
      run: poetry run ruff format sparse_autoencoder --check
    - name: Pytest
      run: poetry run pytest
    - name: Build check
      run: poetry build
